contrib: live position & oracle price updates v1
AdrenaFoundation/frontend pull request #577
Opened 2024-11-24 01:00 UTC by 0xcryptovenom

Enable user positions & pyth oracle price updates on the trading page.

- Based on / requires https://github.com/AdrenaFoundation/frontend/pull/447
- Replaces https://github.com/AdrenaFoundation/frontend/pull/573

2024-11-24 06:07 UTC, adrena-orex requested changes
Some feedback! Thank you for the PR 🙏

2024-11-24 06:07 UTC, adrena-orex commented on src/selectors/streamingTokenPrices.ts
> + * @param state
What's the reason behind using @param and @returns versus typing?

2024-11-24 14:09 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +  }
Ooops good catch, fixing.

2024-11-24 14:11 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +  () => async (dispatch: Dispatch, getState: () => RootState) => {
I prefer using type inference but I don't mind either way, adding a type annotation

2024-11-24 14:14 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +        calculatePnLandLiquidationPrice(position, tokenPrices);
I checked `calculatePnLandLiquidationPrice` it's not supposed to throw, but I can add a try/catch + error log for safety

2024-11-24 14:18 UTC, 0xcryptovenom commented on src/selectors/streamingTokenPrices.ts
> + * @param state
Just using JSDoc comments so the warning shows up in the editor for these selectors, does not replace types, just extra info.
The signature bits is redundant & not useful I can remove it, unless for `selectStreamingTokenPricesForTokensStr` where I'm inclined to keep it because of this comment:

> * @param positionsTokenSymbolsStr a comma separated string list of token symbols to retrive prices for (ie: 'SOL,USDC')

2024-11-24 14:26 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +      let tokenPrices = selectStreamingTokenPrices(getState());
I think ideally we would pick the latest price out of the two ...

But then again it might be best to have a single source of truth for token prices, but that then raises the performance problems.

Maybe I'll add another selector like `selectStreamingTokenPricesFallback`, not sure yet

2024-11-24 14:28 UTC, 0xcryptovenom commented on src/hooks/usePositions.ts
> +            ...positions.flatMap((position) => [
I guess this is where we need to be careful.

My assumption is that we always need to react to the price changes of both the collateral token & the trade token, is this correct?

2024-11-24 14:28 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +            removeSubscription(subscriptionId);
Ah, makes much more sense now thx.

I'll update this

2024-11-24 16:49 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +            removeSubscription(subscriptionId);
Handled in https://github.com/AdrenaFoundation/frontend/pull/577/commits/a614e33e47ad74e74170e9877ba36dbc720fd9bd

Not removing the subscription when a position is deleted or when a position is invalid / cannot be extended.

2024-11-24 23:36 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +      let tokenPrices = selectStreamingTokenPrices(getState());
Handled in https://github.com/AdrenaFoundation/frontend/pull/577/commits/97809019a3568e3224f3b9ee1833262c2fc8f11d:

 - introduce a `selectStreamingTokenPricesFallback` selector:
   - select streaming token prices, fallback to regular token price
 - introduce a `stopStreamingTokenPrices` action + creator:
   - reset the streaming token prices state to initial state
 - dispatch the `stopStreamingTokenPrices` when closing streaming.
 - `fetchUserPositions`, `fetchAndSubscribeToFullUserPositions`, `usePositions` now leverage `selectStreamingTokenPricesFallback` under the hood

2024-11-24 23:53 UTC, 0xcryptovenom commented on src/hooks/usePositions.ts
> +            ...positions.flatMap((position) => [
Re-reading this now..

You're saying my assumption is indeed correct, but actually we don't care about `position.token.symbol` because it doesn't really reflect the trade token, only `getTokenSymbol(position.token.symbol)` does.

I'm making a commit in that sense, let me know how it looks then

2024-11-27 07:45 UTC, 0xcryptovenom commented on src/hooks/usePositions.ts
> +        calculatePnLandLiquidationPrice(
Can the liquidation price change as a result of the position's tokens price changes?

Or can we be efficient here & only re-calculate the position's PnL ?

2024-11-27 23:23 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +      const subscriptionId = connection.onAccountChange(
This appears not to be working as expected, the callbacks are apparently not called:
- when opening a new position
- when closing a position
- probably also not when modifying a position

2024-12-01 03:43 UTC, adrena-orex commented on src/actions/thunks.ts
> +      const subscriptionId = connection.onAccountChange(
that's very problematic then 🤔 should pickup on any change related to the position. If not working we should try an alternative method to pickup changes

2024-12-01 03:43 UTC, adrena-orex commented on src/hooks/usePositions.ts
> +        calculatePnLandLiquidationPrice(
Liquidation price change when borrow fee change `borrowFeeUsd: nativeToUi(interestUsd, USD_DECIMALS),`, which is recalculated in `calculatePositionPnL`

2024-12-01 03:43 UTC, adrena-orex commented on src/pages/trade/index.tsx
>          setTokenA(candidate);
I let you do your magic

2024-12-01 22:49 UTC, 0xcryptovenom commented on src/hooks/usePositions.ts
> +        calculatePnLandLiquidationPrice(
Keeping the calculation of both the PnL & Liquidation price on position's tokens price change.

2024-12-01 23:03 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +      const subscriptionId = connection.onAccountChange(
nvm I'm an idiot

2024-12-02 00:14 UTC, 0xcryptovenom commented on src/actions/thunks.ts
> +      const subscriptionId = connection.onAccountChange(
all fixed.

2024-12-16 12:19 UTC, closed without merging

2024-12-16 12:19 UTC, adrena-orex commented
Created a new PR and deployed